name: nextrelease
description: One-click release publishing by merging an automated PR.
branding:
  icon: package
  color: white
inputs:
  tag_prefix:
    description: The prefix that is on SemVer tags (i.e. "v" or nothing "")
    default: 'v'
  next_branch:
    description: The name for your "nextrelease" branch which is used for the PR
    default: nextrelease
  publish_cmd:
    description: A shell command to run after tagging a release
    default: ""
  prepare_cmd:
    description: Any steps to run before releasing, like replacing version strings in package metadata files.
    default: ""
  github_token:
    description: A GitHub token that can create and modify releases
    required: true
  github_release:
    description: Should be "publish" to create and publish a GitHub Release, "draft" for a draft release that can be published manually, or "skip" for no release.
    default: publish
  release_notes:
    description: Use "generate" to ask GitHub to generate the release notes automatically (using https://docs.github.com/en/rest/reference/repos#generate-release-notes-content-for-a-release).
    default: ""
runs:
  using: composite
  steps:
    - run: pip3 install $GITHUB_ACTION_PATH
      shell: bash
    - run: nextrelease ci
      shell: bash
      env:
        TAG_PREFIX: ${{ inputs.tag_prefix }}
        NEXT_BRANCH: ${{ inputs.next_branch }}
        PUBLISH_CMD: ${{ inputs.publish_cmd }}
        PREPARE_CMD: ${{ inputs.prepare_cmd }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_RELEASE: ${{ inputs.github_release }}
        RELEASE_NOTES: ${{ release_notes }}
