name: test
on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install poetry
    - run: poetry install
    - run: ./scripts/test
